version: "3.9"

networks:
  default:
    name: ${NETWORK_NAME}

volumes:
  backend_data:
    driver: local

services:
  backend:
    container_name: MOTI-PRS-Backend
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
      target: base
    command: ["npm", "run", "start:dev"]
    restart: always
    ports:
      - 3333:3000
